Repository nonamecrackers2/crackers-wither-storm-mod, pull requests merged in 2022-12, with the labels that each got.

#260 Fixed zh_cn translate.
  lang/zh_cn.json
  lang/zh_hk.json
  lang/zh_tw.json
Labels: 1.16.5

#558 1.0.2 translate
  lang/ru_ru.json
Labels: 1.16.5

#733 Update more 1.18 Chinese translate.
  lang/zh_hk.json
  lang/zh_tw.json
Labels: 1.18.2

#734 Update more Chinese translate.
  lang/zh_hk.json
  lang/zh_tw.json
Labels: 1.19
